spring.application.name=mada
server.servlet.context-path=/madavisa
app.base-url=http://localhost:8081

spring.datasource.url=jdbc:postgresql://localhost:5432/madavisa 
spring.datasource.username=postgres
spring.datasource.password=steve
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

# spring.sql.init.mode=always
spring.sql.init.platform=postgresql

server.port=8081